ALTER TABLE voters
  ADD COLUMN IF NOT EXISTS Department VARCHAR(16) NULL AFTER Year,
  ADD COLUMN IF NOT EXISTS Campus     VARCHAR(32) NULL AFTER Department,
  ADD COLUMN IF NOT EXISTS OTP        VARCHAR(8)  NULL AFTER Verified,
  ADD COLUMN IF NOT EXISTS OTPExpiry  DATETIME    NULL AFTER OTP;
